### ISSUE TITLE
Lintnet zsh completion shows only help (install via aqua)

### ISSUE THREAD

**Issue by uta8a** [lintnet/lintnet#528] opened 2024-06-26 14:32 UTC
### lintnet info

```console
$ lintnet info                      
{
  "vesrion": "0.4.7",
  "commit": "dbd81305b0538d5855fb07251463040fce765ca2",
  "runtime": "linux/amd64",
  "root_dir": "/home/uta8a/.local/share/lintnet",
  "env": {}
}
```

(prebuilt binary from GitHub Releases)

```console
$ ./lintnet info     
{
  "vesrion": "0.4.7",
  "commit": "dbd81305b0538d5855fb07251463040fce765ca2",
  "runtime": "linux/amd64",
  "root_dir": "/home/uta8a/.local/share/lintnet",
  "env": {}
}
```

### Overview

lintnet from aqua shows only `help` and `h` when completion(zsh).
When I type `lintnet ` and enter `<tab>`, it shows `help`, `h`.

```console
$ lintnet h<tab>
help  h  -- Shows a list of commands or help for one command
```

lintnet uses urfave/cli/v2 in [pkg/cli/completion.go](https://github.com/lintnet/lintnet/blob/c0d42f25debb3e7cfd79d22eab3f9af63f122f47/pkg/cli/completion.go#L86-L114), so I execute `lintnet --generate-bash-completion`.

```console
$ command -v lintnet 
/home/uta8a/.local/share/aquaproj-aqua/bin/lintnet
$ source <(lintnet completion zsh)
$ lintnet --version       
lintnet version 0.4.7 (dbd81305b0538d5855fb07251463040fce765ca2)
$ lintnet --generate-bash-completion  
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

lintnet from prebuilt binary(GitHub Packages) works fine.

```console
## ./lintnet is downloaded from GitHub Packages
$ ./lintnet --version                 
lintnet version 0.4.7 (dbd81305b0538d5855fb07251463040fce765ca2)
$ ./lintnet --generate-bash-completion
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

I would like to use lintnet installed via aqua.
Could you help me with the cause of this?

### How to reproduce

Please share related files such as lintnet.jsonnet, lint files, and data files.

- No jsonnet files, lint files, and data files.

Executed command and output

```console
$ aqua g -i lintnet/lintnet
$ lintnet --generate-bash-completion
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

### Debug output

```console
$ LINTNET_LOG_LEVEL=debug lintnet --generate-bash-completion
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

### Expected behaviour

```console
$ lintnet --generate-bash-completion
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

### Actual behaviour

```
$ lintnet --generate-bash-completion  
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

### Note

I use Ubuntu 22.04 and zsh.

```console
$ uname -a
Linux rustacean 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by suzuki-shunsuke** [comment] 2024-06-26 15:51
Thank you for your report!
I could reproduce the issue.

```console
$ lintnet --generate-bash-completion  
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

```console
$ $(aqua which lintnet) --generate-bash-completion
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

```console
$ lintnet -v
lintnet version 0.4.7 (dbd81305b0538d5855fb07251463040fce765ca2)

$ aqua -v
aqua version 2.29.0 (9ff65378f0c6197e3130a20f6d978b8a3042b463)
```

M3 Pro

**Comment by suzuki-shunsuke** [comment] 2024-06-26 21:50
:memo:

```console
$ aqua exec -- lintnet --generate-bash-completion 
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

**Comment by suzuki-shunsuke** [comment] 2024-06-26 22:01
I couldn't reproduce the following code.
Interesting.

```go
package main

import (
	"log"
	"os"

	"golang.org/x/sys/unix"
)

func main() {
	if err := core(); err != nil {
		log.Fatal(err)
	}
}

const exePath = "/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/lintnet/lintnet/v0.4.7/lintnet_darwin_arm64.tar.gz/lintnet"

func core() error {
	return unix.Exec(exePath, []string{"lintnet", "--generate-bash-completion"}, os.Environ())
}
```

```console
$ go run main.go
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

**Comment by suzuki-shunsuke** [comment] 2024-06-26 22:25
I added debug logs and tried to output them, but they weren't outputted. 🤔

In case of `lintnet --help`, logs are outputted properly.

```console
$ go run ./cmd/aqua exec -- lintnet --help                    
INFO[0000] ctrl.Exec                                     aqua_version= env=darwin/arm64 exe_name=go program=aqua
INFO[0000] execCommandWithRetry                          aqua_version= env=darwin/arm64 exe_name=go package_name=golang/go package_version=go1.22.4 program=aqua
INFO[0000] execCommand                                  
INFO[0000] executing with x/sys/unix                     args="[go run ./cmd/aqua exec -- lintnet --help]" exe_path=/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.22.4.darwin-arm64.tar.gz/go/bin/go
INFO[0000] ctrl.Exec                                     aqua_version= env=darwin/arm64 exe_name=lintnet program=aqua
INFO[0000] execCommandWithRetry                          aqua_version= env=darwin/arm64 exe_name=lintnet package_name=lintnet/lintnet package_version=v0.4.7 program=aqua
INFO[0000] execCommand                                  
INFO[0000] executing with x/sys/unix                     args="[lintnet --help]" exe_path=/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/lintnet/lintnet/v0.4.7/lintnet_darwin_arm64.tar.gz/lintnet
NAME:
   lintnet - Powerful, Secure, Shareable Linter Powered by Jsonnet. https://lintnet.github.io/

USAGE:
   lintnet [global options] command [command options] 

VERSION:
   0.4.7 (dbd81305b0538d5855fb07251463040fce765ca2)

COMMANDS:
   version     Show version
   lint, l     Lint files
   info        Output the information regarding lintnet
   init        Scaffold configuration file
   test, t     Test lint files
   new         Create a lint file and a test file
   completion  Output shell completion script for bash, zsh, or fish
   help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --log-level value         log level [$LINTNET_LOG_LEVEL]
   --log-color value         Log color. One of 'auto' (default), 'always', 'never' [$LINTNET_LOG_COLOR]
   --config value, -c value  Configuration file path [$LINTNET_CONFIG]
   --help, -h                show help
   --version, -v             print the version
```

But in case of `lintnet --generate-bash-completion `, logs aren't outputted at all.

```console
$ go run ./cmd/aqua exec -- lintnet --generate-bash-completion
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

**Comment by suzuki-shunsuke** [comment] 2024-06-26 22:29
```go
package main

import (
	"log"
	"os"

	"golang.org/x/sys/unix"
)

func main() {
	if err := core(); err != nil {
		log.Fatal(err)
	}
}

const exePath = "/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/lintnet/lintnet/v0.4.7/lintnet_darwin_arm64.tar.gz/lintnet"

func core() error {
	log.Println("executing") // Output log
	return unix.Exec(exePath, []string{"lintnet", "--generate-bash-completion"}, os.Environ())
}
```

```console
$ go run main.go
2024/06/27 07:26:51 executing
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

In case of the simple code, the log was outputted properly.

**Comment by suzuki-shunsuke** [comment] 2024-06-26 22:34
```console
$ ~/go/bin/aqua exec -- echo --generate-bash-completion
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

I replaced `lintnet` with `echo`, then the issue was reproduced.
So this has nothing to do with lintnet.
I guess the option `--generate-bash-completion` is handled by aqua.

**Comment by suzuki-shunsuke** [comment] 2024-06-26 23:30
I wanted to transfer this issue to https://github.com/aquaproj/aqua , but unfortunately seems like we can't transfer issues across organizations.

**Comment by suzuki-shunsuke** [comment] 2024-06-26 23:57
https://github.com/urfave/cli/blob/a1a099bd1c28a2a6beac29123308e87b9606fcc0/app.go#L313-L322

```go
func (a *App) RunContext(ctx context.Context, arguments []string) (err error) {
	a.Setup()


	// handle the completion flag separately from the flagset since
	// completion could be attempted after a flag, but before its value was put
	// on the command line. this causes the flagset to interpret the completion
	// flag name as the value of the flag before it which is undesirable
	// note that we can only do this because the shell autocomplete function
	// always appends the completion flag at the end of the command
	shellComplete, arguments := checkShellCompleteFlag(a, arguments)
```

```console
$ ~/go/bin/aqua exec -- echo --generate-bash-completion
2024/06/27 08:49:05 app name aqua
2024/06/27 08:49:05 arguments [/Users/shunsukesuzuki/go/bin/aqua exec -- echo --generate-bash-completion]
2024/06/27 08:49:05 shellComplete true arguments [/Users/shunsukesuzuki/go/bin/aqua exec -- echo]
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

When `aqua exec -- <command> --generate-bash-completion` is executed,
`aqua exec` executes `App.RunContext`, and `App.RunContext` executes `checkShellCompleteFlag`, then `checkShellCompleteFlag` returns `true`.
This is an issue of urfave/cli/v2.

**Comment by suzuki-shunsuke** [comment] 2024-06-27 03:10
I'll report this issue and send a pull request to urfave/cli.

**Comment by suzuki-shunsuke** [comment] 2024-06-29 07:08
I created pull requests to urfave/cli and I'm waiting for review.

- PR for urfave/cli/v2: https://github.com/urfave/cli/pull/1938
- PR for urfave/cli/v3: https://github.com/urfave/cli/pull/1933 : we're using v2, so this pr isn't related to this issue

**Comment by suzuki-shunsuke** [comment] 2024-06-29 22:12
PRs were merged. We're waiting for new release of urfave/cli/v2.
https://github.com/urfave/cli/compare/v2.27.2...v2-maint

**Comment by suzuki-shunsuke** [comment] 2024-07-14 05:40
aqua v2.29.1 is out 🎉 

https://github.com/aquaproj/aqua/releases/tag/v2.29.1

I've confirmed this issue has been solved.

```console
$ which lintnet
/Users/shunsukesuzuki/.local/share/aquaproj-aqua/bin/lintnet

$ lintnet --generate-bash-completion
version:Show version
lint:Lint files
l:Lint files
info:Output the information regarding lintnet
init:Scaffold configuration file
test:Test lint files
t:Test lint files
new:Create a lint file and a test file
completion:Output shell completion script for bash, zsh, or fish
help:Shows a list of commands or help for one command
h:Shows a list of commands or help for one command
```

**Closed by suzuki-shunsuke** 2024-07-14 05:40 UTC
Labels: bug
